# -*- coding: utf-8 -*-
"""Rasa_intern_work.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l4jRnf54vNStn5Jf06JeBG3sNAlekJLg
"""

!pip install rasa_nlu
!pip install -U spacy
!pip install sklearn_crfsuite

!pip install spacy==2.3.5
!python -m spacy download en_core_web_sm
!python -m spacy link en_core_web_sm en

from rasa_nlu.training_data import load_data
from rasa_nlu.config import RasaNLUModelConfig
from rasa_nlu.model import Trainer
from rasa_nlu import config
import spacy
from rasa_nlu.model import Interpreter

#4 Training Utterances with RASA
train_data = load_data('rasa_dataset.json')
trainer = Trainer(config.load("yaml_config.yaml"))
trainer.train(train_data)
model_dir=trainer.persist('/projects/')

files=open('testfile.txt', 'r')
Lines=files.readlines()

#1 Intent classification.
intent_classifier=Interpreter.load(model_dir)
for sent in Lines:
  values=intent_classifier.parse(sent)
  print(values['intent']['name'])

#2 Meaningful entities 
nlp = spacy.load('en')
with open('testfile.txt', 'r') as line:
  sent=line.read()
  docx=nlp(sent)
  for chars in docx.ents:
    print(f'Entity for word {chars.text} ',chars.label_)

#3 Tag utterence with entities
for sent in Lines:
  docx=nlp(sent)
  for chars in docx.ents:
    print(f'Entity for word {chars.text} ',chars.label_)